name: GitHub Actions Demo
on: [push]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install Requirements"
        run: pip install -r requirements.txt

      - name: "Run Tests"
        run: pytest
  CD:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/main'
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install Requirements"
        run: pip install -r requirements.txt

      - name: "Create AWS Key File"
        run: echo "${{ secrets.AWS_KEY }}" > aws.key

      - name: "Debug"
        run: |
          echo ${{ vars.AWS_IP }}
          ls -la

      - name: "Deploy Files"
        run: scp -i aws.key __init__.py requirements.txt ubuntu@3.14.130.103:/home/ubuntu/deploy
