name: GitHub Actions Demo
on: [push]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install Requirements"
        run: pip install -r requirements.txt

      - name: "Run Tests"
        run: pytest
  CD:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/main'
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install Requirements"
        run: pip install -r requirements.txt
        
      - name: "Debug"
        run: echo "debug"
