name: GitHub Actions Demo
on: [push]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install Requirements"
        run: pip install -r requirements.txt

      - name: "Run Tests"
        run: pytest
  CD:
    runs-on: ubuntu-latest
    # needs:
    #   - "CI"
    env:
      DEPLOY_HOST: ubuntu@${{ vars.AWS_IP }}:/home/ubuntu/deploy
    # if: github.ref == 'refs/heads/main'
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Create AWS Key File"
        run: |
          echo "${{ secrets.AWS_KEY }}" > aws.key
          chmod 0600 aws.key
          mkdir ~/.ssh
          ssh-keyscan -H ${{ vars.AWS_IP }} > ~/.ssh/known_hosts

      - name: "Debug"
        run: |
          echo ${{ vars.AWS_IP }}
          ls -la

      - name: "Deploy Files"
        run: scp -i aws.key __init__.py requirements.txt "$DEPLOY_HOST"

      - name: "Install Pip"
        run: |
          ssh -i aws.key "$DEPLOY_HOST" 'sudo apt install python3-pip -y'
      
      - name: "Install Dependencies"
        run: |
          ssh -i aws.key "$DEPLOY_HOST" 'pip install -r requirements.txt --break-system-packages'